### ISSUE TITLE
Constructing an instance of this class initializes the display system.

### ISSUE THREAD

**Issue by audioplastic** [a-n-t-h-o-n-y/CPPurses#18]
Not true. Simply mentioning an instance in the code compiles it in and there is some static initialisation that launches the display system. 

See my issues here . . .

https://stackoverflow.com/questions/54328405/code-being-executed-inside-of-unsatisfied-false-if-statement

**Comment by audioplastic** [comment]
In other words ... why all the globals. Totally screws a program where you might want to display help in the console without firing up full console control

**Comment by a-n-t-h-o-n-y** [comment]
Thanks for mentioning this, it's not something I'd tested, and didn't realize it is still initializing. I'll look into it.

**Comment by audioplastic** [comment]
Awesome. Many thanks

**Comment by a-n-t-h-o-n-y** [comment]
The latest commits on master should patch this up.

Curses mode will now initialize on a call to `System::run()`, and will uninitialize itself when that call returns. This allows you to open and close the curses mode multiple times. `System::terminal.initialize()` and `System::terminal.uninitialize()` can also be called directly to do this.

Just a heads up, there is an API change to setting the head widget, instead of `Tree::set_head(...)` the call is now `System::set_head(...)`. And with these new commits you'll want to update the submodules in git. `git submodule update --recursive --remote` should do the trick.

Let me know if you have any problems with this.
