### ISSUE TITLE
Minor build breaking typo in demos

### ISSUE THREAD

**Issue by MuteCodemonkey** [a-n-t-h-o-n-y/CPPurses#26]
Specifically where I encountered it was in the chess demo where it was trying to link to: "/usr/local/lib64/liblibcppurses.a" while I believe it should be linking to: "/usr/local/lib/libcppurses.a" as that was the where it was installed.

OS: Ubuntu 19.04
arch: x64

**Comment by a-n-t-h-o-n-y** [comment]
That link command in `CPPurses/demos/chess/CMakeLists.txt` is not actually being used in the build, the build commands are in `CPPurses/demos/CMakeLists.txt`.

It's there because it is importing the chess demo as a submodule and that was the build command from that project. If you are trying to build the chess app on its own, then that cmake file is broken for most environments, but the demos are meant to be built together using the cmake file in the `demos/` folder.

Are you encountering this error when you use the `CMakeLists.txt` file in the project's root directory?

**Comment by MuteCodemonkey** [comment]
Well I guess I should have been more specific in my header the typo does NOT effect the compilation when compiling from the master, but rather when attempting to compile the demos individually.

**Comment by a-n-t-h-o-n-y** [comment]
The demos have to be built as a single executable, I don't have any plans to change this at the moment. Even though there is a `CMakeLists.txt` file in the chess directory it is not used or supported in this library.
