### ISSUE TITLE
Howto Link CPPurses To project

### ISSUE THREAD

**Issue by williamkibira** [a-n-t-h-o-n-y/CPPurses#5]
Hello , again . how can i add cppurses to a cmake project ?

**Comment by a-n-t-h-o-n-y** [comment]
For the latest commit on the master branch, this is how I would link with cppurses, if it is installed:
```
...
add_executable(main main.cpp)
target_link_libraries(main -lcppurses -lncurses -pthread)
...
```
If you have the library archive file local to your project, then you can specify the path to it directly instead of `-lcppurses`.

I have very recently updated the master branch and the library archive name has been changed, so if you are using an older commit the linker flag would be `-llibcppurses`. And just a heads up, the newest commit on master has breaking API changes.
